#!/usr/bin/python

from mininet.topo import Topo

class MyTopo(Topo):
  def __init__(self):
      # Initialize topology
      Topo.__init__(self)
      
      # Create template host, switch, and link
      hconfig = {'inNamespace':True}
      host_link_config = {}
      
      # Create switch nodes
      for i in range(4):
          sconfig = {'dpid': "%016x" % (i+1)}
          self.addSwitch('s%d' % (i+1), **sconfig)
      
      # Create host nodes
      for i in range(8):
          self.addHost('h%d' % (i+1), **hconfig)
      
      # Add switch links
      self.addLink('s1', 's2')
      self.addLink('s1', 's3')
      self.addLink('s1', 's4')
      self.addLink('s2', 's4')
      self.addLink('s2', 's3')
      self.addLink('s3', 's4')
      
      # Add host links
      self.addLink('h1', 's1', **host_link_config)
      self.addLink('h2', 's1', **host_link_config)
      self.addLink('h3', 's2', **host_link_config)
      self.addLink('h4', 's2', **host_link_config)
      self.addLink('h5', 's3', **host_link_config)
      self.addLink('h6', 's3', **host_link_config)
      self.addLink('h7', 's4', **host_link_config)
      self.addLink('h8', 's4', **host_link_config)
      
topos = { 'mytopo': ( lambda: MyTopo() ) }
